### ISSUE TITLE
Adding CODE OF CONDUCT file , CONTRIBUTING  file and uodate README file accordingly

### ISSUE THREAD

**Issue by akrish4** [Abhijit2505/Portfolio-App-Template#16]
Hi @Abhijit2505 
This is a great project as portfolio are very important , But I found that there is no contributing file and code of conduct file in this repository , which are needed for any repository so that a begineer or any dvevelper can follow the code of conduct and understand the contriburing guideliness and can get going 
Kindly assign me this issue

**Comment by akrish4** [comment]
@Abhijit2505 
Kindly assign me this issue

**Comment by Abhijit2505** [comment]
Well, currently we don't want these files.

Thanks.
